//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-M9LQ60VB\\SQLEXPRESS;Initial Catalog=UserManagement;Persist Sec" +
            "urity Info=True;User ID=sa;Password=123456789")]
        public string UserManagementConnectionString {
            get {
                return ((string)(this["UserManagementConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-UBANSNP;Initial Catalog=UserManagement;Persist Security Info=" +
            "True;User ID=sa;Password=123;TrustServerCertificate=True")]
        public string UserManagementConnectionString1 {
            get {
                return ((string)(this["UserManagementConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-M9LQ60VB\\SQLEXPRESS;Initial Catalog=BuildStoreManager;Persist " +
            "Security Info=True;User ID=sa;Password=123456789")]
        public string BuildStoreManagerConnectionString {
            get {
                return ((string)(this["BuildStoreManagerConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-UBANSNP;Initial Catalog=UserManagement;Persist Security Info=" +
            "True;User ID=sa;Password=123;Encrypt=True;TrustServerCertificate=True")]
        public string UserManagementConnectionString2 {
            get {
                return ((string)(this["UserManagementConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-UBANSNP;Initial Catalog=BuildStoreManager;Persist Security In" +
            "fo=True;User ID=sa;Password=123;TrustServerCertificate=True")]
        public string BuildStoreManagerConnectionString1 {
            get {
                return ((string)(this["BuildStoreManagerConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-UBANSNP;Initial Catalog=BuildStoreManager;Persist Security In" +
            "fo=True;User ID=sa;Password=123;Encrypt=True;TrustServerCertificate=True")]
        public string BuildStoreManagerConnectionString2 {
            get {
                return ((string)(this["BuildStoreManagerConnectionString2"]));
            }
        }
    }
}
